Assets/Player/Scripts/PlayerController.cs, Assets/Settings/URP-HighFidelity-Renderer.asset, Assets/_Scenes/[HalenTestScenes]/[PlayerControllerTest].unity
Edited PlayerControllerTest scene.
Edited PlayerController script.
=> Added camera logic

.gitignore.bak, Assets/LevelObjects/Prefabs/LaunchPad.prefab, Assets/LevelObjects/Scripts/Killzone.cs, Assets/LevelObjects/Scripts/Killzone.cs.meta, Assets/LevelObjects/Scripts/LaunchPad.cs, Assets/Player/Scripts/PlayerController.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
Tried to update the gitignore to ignore the probuilder project settings file and failed.
Launchpads completed.
Edited player controller to have a separate velocity for objects that control the player's velocity;
Added Killzone script for triggers that instantly kill the player
=> Gitignore failure and Level Objects

Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab
Added remaining steel poles under the mesh floors, and walls (interior room 2) and also added the front part of microwave.
=> Added remaining prefabs for room 2

Assets/LevelObjects/Art/Prefabs/GravityTransformerModel.prefab, Assets/LevelObjects/Art/Prefabs/GravityTransformerModel.prefab.meta, Assets/LevelObjects/Art/Prefabs/RepeatGravityTransformerModel.prefab, Assets/LevelObjects/Art/Prefabs/RepeatGravityTransformerModel.prefab.meta, Assets/LevelObjects/Events/ChangeGravityEvent.cs, Assets/LevelObjects/Events/ChangeGravityEvent.cs.meta, Assets/LevelObjects/Events/RepeatingChangeGravityEvent.cs, Assets/LevelObjects/Events/RepeatingChangeGravityEvent.cs.meta, Assets/LevelObjects/Prefabs/GravityTransformer.prefab, Assets/LevelObjects/Prefabs/GravityTransformer.prefab.meta, Assets/LevelObjects/Prefabs/RepeatingGravityTransformer.prefab, Assets/LevelObjects/Prefabs/RepeatingGravityTransformer.prefab.meta, Assets/LevelObjects/Prefabs/TriggerBox.prefab, Assets/LevelObjects/Prefabs/TriggerBox.prefab.meta, Assets/LevelObjects/Scripts/TriggerBox.cs, Assets/LevelObjects/Scripts/TriggerBox.cs.meta, Assets/Player/Scripts/PlayerStatus.cs, Assets/UI/Prefabs/GravityChangeCanvas.prefab, Assets/UI/Scripts/GravityIndicatorUI.cs, Assets/Utilities/LevelManagement/ScriptableObjects.meta, Assets/Utilities/LevelManagement/Scripts/LevelData.cs, Assets/_Scenes/[EmilyTest]/[LevelObjectTestEMILY].unity, Assets/_Scenes/[EmilyTest]/[LevelObjectTestEMILY].unity.meta
Made the events for the gravity switching as well as adding trigger boxes and prefabs for the gravity transformer and the repeating gravity transformer
=> Emily gravity Events

Assets/LevelObjects/Events/ChangeGravityDelayedEvent.cs, Assets/LevelObjects/Events/ChangeGravityDelayedEvent.cs.meta, Assets/LevelObjects/Events/ChangeGravityEvent.cs, Assets/LevelObjects/Events/SetInactiveEvent.cs, Assets/LevelObjects/Events/SetInactiveEvent.cs.meta, Assets/LevelObjects/InteractableObjects/Scripts/RepeatingEventObject.cs, Assets/LevelObjects/InteractableObjects/Scripts/RepeatingEventObject.cs.meta, Assets/LevelObjects/MovingLevelObjects/Scripts/MovingLevelObject.cs, Assets/LevelObjects/MovingLevelObjects/Scripts/SpinningObject.cs, Assets/LevelObjects/Scripts/LaunchPad.cs, Assets/Player/Prefabs/Player Prefab.prefab, Assets/Player/Scripts/FirstPersonCameraController.cs, Assets/Player/Scripts/PlayerController.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
Split Change Gravity event into a regular and Change Gravity Delayed event. Created SetInactive event.
Created Repeating Event Object which repeatedly pulses whatever events it has. Based on Interactable object, so works like a button. Launchpads now should launch rigidbodies.
Got rid of camera jitter/stutter.
=> Level objects and Player stuff

Assets/LevelObjects/Events/ChangeGravityEvent.cs, Assets/_Scenes/[YashTest].meta, Assets/_Scenes/[YashTest]/[MicrowavePrototyping01] 1.unity.meta
- Edited ChangeGravityEvent.cs to try and flip camera (Stops player from being launched i think so thats something)
- Made a duplicate of the scene for Yash to do some lighting on inside folder [YashTest]
=> Got gravity switching somewhat stable I think

Assets/Levels/Microwave/Art/Prefabs/Fan_BaseLess.prefab, Assets/Player/Scripts/PlayerCheckInteractable.cs, Assets/Player/Scripts/PlayerCheckInteractable.cs.meta, Assets/Utilities/Checkpoints/Scripts/Checkpoint.cs, Assets/Utilities/GameManager/Scripts/GameManager.cs, Assets/Utilities/LevelManagement/Scripts/LevelData.cs, ProjectSettings/EditorBuildSettings.asset
Quick fixes and polish to the prototype level, edited interaction stuff with a new script and object on the player to enable and disable an interact canvas
=> Quick polish to prototype level and made indicator for interact canvas

Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab
updated room1artprefab in microwaveprototyping01 scene, sending to main so archie can work on it
=> updated microwave level room 1

Assets/Player/Art/Prefabs/PlayerModel.prefab, Assets/Player/Prefabs/3P Player Prefab.prefab, Assets/Player/Scripts/PlayerController.cs, Assets/_Scenes/[HalenTestScenes]/[3rdPersonCameraTest].unity
Player now rotates to face the direction its moving correctly-ish.
=> Player body rotation done

Assets/Sound/Prefabs.meta, Assets/Sound/Prefabs/SFXController.prefab, Assets/Sound/Prefabs/SFXController.prefab.meta, Assets/Sound/Prefabs/SoundClipObject.prefab, Assets/Sound/Prefabs/SoundClipObject.prefab.meta, Assets/Sound/Scripts/SFXController.cs, Assets/Sound/Scripts/SFXController.cs.meta, Assets/Sound/Scripts/SoundClipObject.cs, Assets/Sound/Scripts/SoundClipObject.cs.meta, Assets/_Scenes/Templates/3rdPersonPlayerControllerTemplate.unity, Assets/_Scenes/Templates/ExternalPlayeControllerTemplate.scenetemplate, ProjectSettings/ProjectSettings.asset
Singleton SFX Controller and sound instantiation object added.
=> Added sound system

Assets/Levels/LevelManagement/Editor/LevelManagerEditor.cs, Assets/Menus/Prefabs/PauseMenuCanvas.prefab, Assets/Menus/Prefabs/PauseMenuCanvas.prefab.meta, Assets/Menus/Prefabs/UIMenuCanvas.prefab, Assets/Menus/Prefabs/UIMenuCanvas.prefab.meta, Assets/Menus/Scripts/EventSystemManager.cs, Assets/Menus/Scripts/EventSystemManager.cs.meta, Assets/Menus/Scripts/PauseMenu.cs, Assets/Menus/Scripts/PauseMenu.cs.meta, Assets/Menus/Scripts/UIMenu.cs, Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity.meta
Started work on pause menu, will stop for now to work on player death
=> Emily pause menu 26/08

Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab
- realigned objects in room 1 artprefab
- realigned colliders in scene
=> updates to microwave

Assets/Levels/Scripts/Checkpoint.cs, Assets/Player/Scripts/PlayerStatus.cs, Assets/Player/UI/Prefabs/PlayerSpawnUI.prefab, Assets/Player/UI/Prefabs/PlayerSpawnUI.prefab.meta, Assets/Player/UI/Scripts/PlayerDeathUI.cs, Assets/Player/UI/Scripts/PlayerSpawnUI.cs, Assets/Player/UI/Scripts/PlayerSpawnUI.cs.meta, Assets/Player/UI/Shaders/HurtStaticMat.mat, Assets/_Scenes/[EmilyTest]/[UIDeathTest].unity
Made a spawn animation to instantiate that will destroy itself after it has played also made changes to the checkpoint script in preparation to respawn the player
=> Prepared checkpoint for respawning player and made spawn animation

Assets/GameManager/Scripts/GameManager.cs, Assets/Levels/LevelManagement/Editor/LevelManagerEditor.cs, Assets/Levels/LevelManagement/Scripts/LevelManager.cs, Assets/Levels/Scripts/Checkpoint.cs, Assets/Menus/Scripts/PauseMenu.cs, Assets/Player/Scripts/PlayerStatus.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
LevelManager has a new Spawn function which will spawn the player to the correct spot (Current active checkpoint) and play animations dying will also call a respawn to happen
pause menu should be all working now
=> Fixed respawning to checkpoints and spawning working with animations

Assets/LevelObjects/Prefabs/Screw.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/ScrewSocket/ANIMATION/Power_Socket_MDL.controller, Assets/Player/Prefabs/InteractionObject.prefab
- changes to Microwaveprototyping01
- screw prefab
- interaction canvas and object
=> final room 1 changes to build

Assets/GameManager/Scripts/GameManager.cs, Assets/Levels/LevelManagement/Scripts/LevelManager.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity, ProjectSettings/TagManager.asset
Edited LevelManager and GameManager to add an async function to load scene in background so it applies all references correctly when reloading scene
=> Added an async call function to reload scene properly

Assets/Levels/Microwave/Art/Materials/Gate/GateDoors_MAT.mat, Assets/Levels/Microwave/Art/Materials/Gate/GateFrames_MAT.mat, Assets/Levels/Microwave/Art/Materials/SocketA/PowerSocketAndScrew_MAT.mat, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab
made some materials more metallic, turned on colliders
=> collider and material fixes

Assets/LevelObjects/EventObjects/Scripts/ToggleObject.cs, Assets/LevelObjects/EventObjects/Scripts/TriggerObject.cs, Assets/LevelObjects/PickupObjects/Scripts/PlantableScrew.cs, Assets/LevelObjects/Scripts/EventObject.cs, Assets/Player/Interaction/Scripts/PlayerInteraction.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
pressure plate wasnt working because events werent being called; needed to override isActive.
=> fixed event object organisation

Assets/LevelObjects/EventObjects/Scripts/ObjectReceptacle.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
isActive call was setting m_canInteract to false.
=> fixed receptacle

Assets/LevelObjects/Art/Prefabs/PressurePlateModel.prefab, Assets/LevelObjects/EventObjects/Prefabs/PressurePlate/Animation/OnActivate.anim, Assets/LevelObjects/EventObjects/Prefabs/PressurePlate/Animation/PressurePlate.controller, Assets/LevelObjects/EventObjects/Prefabs/PressurePlate/Animation/PressurePlate.controller.meta, Assets/LevelObjects/EventObjects/Prefabs/PressurePlate/PressurePlate.prefab, Assets/LevelObjects/EventObjects/Prefabs/PressurePlate/Room1PressurePlate.prefab, Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab
- changed pressureplates to use the original and not the variant, added walkable and base activation events
- changes to microwave scene, all room1 and 2 parent prefabs
- readded level objects to room 2, part 1
=> Pressure plate fix, additions to to room 1 and 2 level objects

Assets/LevelObjects/EventObjects/Prefabs/Repeating Object.prefab, Assets/LevelObjects/EventObjects/Prefabs/Repeating Object.prefab.meta, Assets/LevelObjects/EventObjects/Scripts/RepeatingEventObject.cs, Assets/LevelObjects/EventObjects/Scripts/RepeatingEventObject.cs.meta, Assets/Player/Art/Animations/Robot_ANIM_Controller.controller, Assets/Player/Art/Prefabs/PlayerModel.prefab, Assets/Player/Prefabs/External Player Controller.prefab, Assets/Player/Scripts/AnimationController.cs, Assets/Player/Scripts/AnimationController.cs.meta, Assets/Player/Scripts/PlayerController.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
Created Repeating Event Object.
Set up Player animator controller with walking animation. Created AnimationController component to handle controlling an animator through scripts for anything with an animation.
=> Repeating Object and Animation

Assets/Levels/Scripts/ScreenShaderController.cs, Assets/Levels/Scripts/ScreenShaderController.cs.meta, Assets/Levels/Tasks.meta, Assets/Levels/Tasks/Prefabs.meta, Assets/Levels/Tasks/Scripts.meta, Assets/Levels/Tasks/Scripts/TaskItem.cs, Assets/Levels/Tasks/Scripts/TaskItem.cs.meta, Assets/Levels/Tasks/Scripts/TaskListManager.cs, Assets/Levels/Tasks/Scripts/TaskListManager.cs.meta, Assets/Player/Prefabs/External Player Controller.prefab, Assets/Player/Scripts/PlayerStatus.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Added a seperate shader controller which will stop the renderer from constantly changing the material in the assets folder
=> Added a fix for the shader material appearing in commits

Assets/Levels/LevelManagement/Scripts/LevelManager.cs, Assets/Levels/Tasks/Scripts/TaskItem.cs, Assets/Levels/Tasks/Scripts/TaskListManager.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Got rid of single line at the start of SpawnPlayer() function in LevelManager that was causing errors to throw
=> Got rid of line throwing error causing spawn UI not to appear

Assets/Menus/Scripts/UIMenu.cs, Assets/_Scenes/[EmilyTest]/[BetterPauseMenu].unity, Assets/_Scenes/[EmilyTest]/[BetterPauseMenu].unity.meta, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Slightly updated layout of UIMenu Editor
now the tweening positions are edited with sliders Also fixed up code to align UI to the correct scale of any screen
=> Made fixes to UI scaling that was causing it to not scale in builds

Assets/Camera/Prefabs/CM 3rdPerson Normal.prefab, Assets/LevelObjects/EventObjects/Scripts/TriggerObject.cs, Assets/LevelObjects/Scripts/Killzone.cs, Assets/LevelObjects/Scripts/ObjectSpawner.cs, Assets/Player/Interaction/Prefabs/InputIcons.prefab, Assets/Player/Interaction/Prefabs/InteractionCanvas.prefab, Assets/Player/Interaction/Scripts/PlayerInteraction.cs, Assets/Player/Prefabs/InteractionObject.prefab, Assets/_Scenes/Templates/3rdPersonPlayerControllerTemplate.unity, Assets/_Scenes/Templates/ExternalPlayeControllerTemplate.scenetemplate, Assets/_Scenes/[HalenTestScenes]/[NewMicrowaveLevel].unity
Fixed bug with interaction system that made TriggerObject not do anything.
Fixed a reference in the template scene. Input Icons object was not setup in the PlayerInput callbacks to update the current control scheme.
Pickup objects can now be destroyed by kill zones.
Object Spawner's spawnAtStart now instantly respawns objects if they are destroyed.
Increased max height of normal vcam.
=> interaction bug and pickups

Assets/Menus/Prefabs/PauseMenuCanvas.prefab, Assets/_Scenes/[EmilyTest]/[BetterPauseMenu].unity
Prefab of the pause menu should be adjusted now to fix issues reported where the pause menu would just sit in the corner
=> Updated pause menu prefab to fix alignment issues

Assets/GameManager/Scripts/GameManager.cs, Assets/Menus/Prefabs/PauseMenuCanvas.prefab, Assets/Menus/Scripts/PauseMenu.cs, Assets/Menus/Scripts/UIMenu.cs, Assets/Player/Scripts/PlayerStatus.cs, Assets/_Scenes/[EmilyTest]/MenuScene.unity, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity, ProjectSettings/TagManager.asset
Fixed pause menu not working because of error in grabbing the wrong menu in start up
Also added Reset to Checkpoint button in the pause menu
Started working on the Level selector in main menu
=> Emily pause menu fix 23/09

Assets/Levels/Microwave/Art/Prefabs/PillarPlatform 1.prefab, Assets/Levels/Microwave/Art/Prefabs/PillarPlatform 1.prefab.meta, Assets/Levels/Microwave/RoomPrefabs/HalenRoom.prefab
Started adding/modifying prefabs room 2. Such as: Pillar walls and mesh floors in halen's room.
=> Started adding prefabs to room 2

Assets/Decals/Arrow.mat, Assets/Decals/TestDecal.mat, Assets/Decals/TestDecal.mat.meta, Assets/Levels/LevelManagement/ScriptableObjects/MicrowaveLevelData.asset, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab
- Re-drag'd the new player controller from the template scene into microwaveprototyping01 scene
- added liam's finished room 2 prefab
- fixed microwaveleveldata object so the player doesnt spawn upside down
=> Fixes and updates to microwave scene

Assets/Player/Prefabs/External Player Controller.prefab, Assets/_Scenes/[HalenTestScenes]/[NewMicrowaveLevel].unity
Interaction object is now a child of Player Model so it rotates with the player.
=> Changed player prefab structure

Assets/Menus/Prefabs/EventSystemManager.prefab, Assets/Menus/Prefabs/PauseMenuCanvas.prefab, Assets/_Scenes/MenuScene.unity, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Pause menu will no longer deselect if you click off of it
=> Fixed pause menu deselecting

Assets/Levels/Scripts/Checkpoint.cs, Assets/Menus/Scripts/CRTScreenEffect.cs, Assets/Menus/Scripts/CRTScreenEffect.cs.meta, Assets/Player/UI/Scripts/PlayerSpawnUI.cs
PlayerDeathUI and PlayerSpawnUI updated to ignore timescale Added CRT close effect that keeps the screen black Removed debug logs from checkpoint
=> Updated previous screen effects and added permanent close effect

Assets/Menus/Scripts/ScreenFadeEffect.cs, Assets/Menus/Scripts/ScreenFadeEffect.cs.meta, Assets/Player/Scripts/PlayerStatus.cs, Assets/Player/UI/Scripts/PlayerSpawnUI.cs
Updated PlayerSpawnUI to inherit from a new ScreenFadeEffectClass Updated PlayerStatus to activate the spawn effect
=> Added ScreenFade class and set up player to play spawn effect

Assets/ImportedAssets.meta, Assets/Menus/Prefabs/EventSystemManager.prefab, Assets/Player/Interaction/Prefabs/InputIcons.prefab, Assets/Player/Interaction/Scripts/PlayerInputIcons.cs, Assets/_Scenes/MenuScene.unity, Assets/_Scenes/PlayerScene.unity
Set up handling for the Input Icons to work across the main menu and player scenes.
=> Input Icons and Player Input

Assets/LevelObjects/MovingLevelObjects/Prefabs/Fan_BaseLess.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/EnergyCables/Cable01/Animation/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/GateAIndicators/AnimationL/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/GateAIndicators/AnimationR/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/WirePulses/WirePulseA/Animation/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/WirePulses/WirePulseB/Animation/OnActivate.anim, Assets/Levels/Microwave/Art/Materials/MeshFloorNew/lambert1.mat, Assets/Levels/Microwave/Art/Materials/Room1Walls/Room1Floor_MAT.mat, Assets/Levels/Microwave/Art/Materials/Room2_Pillars/Room2_Pillars_MAT.mat, Assets/Levels/Microwave/Art/Prefabs/PillarPlatform 1.prefab, Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/HalenRoom.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Settings/PostProcessing/SampleSceneProfile.asset, Assets/Settings/URP/PlaceholderSettings/URP-HighFidelity-Renderer.asset, Assets/_Scenes/MenuScene.unity, Assets/_Scenes/[BraydenTestScenes]/BackPlayerSetup.unity, Assets/_Scenes/[BraydenTestScenes]/BackPlayerSetup.unity.meta, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/ProjectSettings.asset
tuned emission intensities for room 1 animated objects, added yash' lighting, small collider fixes to room 2, tweaked placements in the room 1 art prefab
=> Fixes, changes, and additions for Alphacon safety build

Assets/Camera/Prefabs/CM 3rdPerson Normal.prefab, Assets/LevelObjects/EventObjects/Scripts/Interactable.cs, Assets/LevelObjects/HazardObjects/Scripts/HazardObject.cs, Assets/Levels/Checkpoints/Prefabs/Checkpoint.prefab, Assets/Levels/Checkpoints/Scripts/Checkpoint.cs, Assets/Levels/Checkpoints/Scripts/CheckpointTeleporter.cs, Assets/_Scenes/PlayerScene.unity
Player can now interact with a checkpoint to bring up the teleport canvas.
=> Interact logic for checkpoint teleporter

Assets/Decals/Decal_Parent.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform.meta, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/Animation.meta, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/Animation/ExtendingPlatform.controller, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/Animation/ExtendingPlatform.controller.meta, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/Animation/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/Animation/OnActivate.anim.meta, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/ExtendingPlatform.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/ExtendingPlatform/Room1Gate_ExtendingPlatform/ExtendingPlatform.prefab.meta, Assets/Levels/Microwave/AnimatedObjectsFolder/Fan_Access/Animation/OnDeactivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/Fan_Access/Fan_Access.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/GateA/Animation/OnActivate.anim, Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab
- fixed the colliders for camera clipping
- fixed fan
- added extending platform at the door
=> room 1 feedback implementation complete

Assets/Camera/Prefabs/CM 3rdPerson Normal.prefab, ProjectSettings/TagManager.asset
Changed Cinemachine collider to use the Pull Forward strategy instead and now has intended behaviour.
=> New camera discovery

Assets/Levels/Scripts/ScreenShaderController.cs
Blit error, where it's trying to find a shader when loading the error has been fixed
=> Fixed Blit error on level load

Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/_Scenes/PlayerScene.unity
- blockout for first gravity section in room 2 (unfinished)
- changes to smoothing in player gravity flip
=> progress update to first section in room 2

Assets/Levels/Microwave/Art/Materials/AirDuct/Modular/AirDuctClosed_MAT.mat, Assets/Levels/Microwave/Art/Materials/AirDuct/Modular/AirDuctClosed_MAT.mat.meta, Assets/Levels/Microwave/Art/Models/3D Assets/Final Models/AirDuct_modular_New.fbx.meta, Assets/Levels/Microwave/Art/Prefabs/Air Duct Vent Modular.prefab, Assets/Levels/Microwave/Art/Prefabs/Air Duct Vent Modular.prefab.meta, Assets/Levels/Microwave/Art/Prefabs/ModFencev3_Emissive.prefab, Assets/Levels/Microwave/Art/Prefabs/ModFencev3_Emissive.prefab.meta, Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab, Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab
implemented new modular air duct, finalized colliders in room 2
=> final touches to first section in room 2

Assets/LevelObjects/PickupObjects/Prefabs/Screw.prefab, Assets/Levels/Microwave/Art/Models/3D Assets/Final Models/HazardFloor/FloorCover_MAT.mat, Assets/Levels/Microwave/Art/Models/3D Assets/Final Models/HazardFloor/HazardFloor_MAT.mat, Assets/Levels/Microwave/Art/Prefabs/HazardFloor.prefab, Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/UnityTechnologies/ParticlePack/EffectExamples/Smoke & Steam Effects/Materials/wispySmoke.mat
- screw collider fix
- room 2 hazard floor decals implemented (not finished)
- added buttons to room 1
=> various fixes & changes to room 1 and 2 & screw

Assets/Decals/Decal_Parent.prefab, Assets/FinalLavaFloor/DecalsCracks (1).prefab, Assets/FinalLavaFloor/RisingSteam_v2.prefab, Assets/FinalLavaFloor/RisingSteam_v2.prefab.meta, Assets/LevelObjects/PickupObjects/Prefabs/Screw.prefab, Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/Lighting/Lighting & VFX.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/UnityTechnologies/ParticlePack/EffectExamples/Smoke & Steam Effects/Materials/wispySmoke.mat
- finalized cracks in room 2
- added the steam particles in room 2
- reverted changes to the prefab in room 1/2 to fix functonality, but removed the task list stuff
- removed the mesh colliders from the grills
- shrunk the screw size as it was causing problems with jumping and player controller
- added hazard tape to the big fans' walls
=> fixes and changes to room 2

Assets/LevelObjects/Art/ParticlesPrefab.meta, Assets/LevelObjects/Art/ParticlesPrefab/HeatCoilSparks.prefab, Assets/LevelObjects/Art/ParticlesPrefab/HeatCoilSparks.prefab.meta
Made a new prefab for heat distortion spark
=> Made a new prefab for heat distortion spark

Assets/LevelObjects/PickupObjects/Scripts/MeshDissolver.cs, Assets/Player/Art/Animations/Robot_ANIM_Controller.controller, Assets/Player/Art/Prefabs/PlayerModel.prefab, Assets/Player/Prefabs/External Player Controller.prefab, Assets/_Scenes/PlayerScene.unity
Put the new model onto the player.
Updated the animator to use the new model/animation.
=> Set up new player model

Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab
Added some models to room 3 and edited it a bit.
=> Edited room 3 prefab

Assets/Levels/Settings.meta, Assets/Levels/Settings/PlayerSettings.prefab, Assets/Levels/Settings/PlayerSettings.prefab.meta, Assets/Levels/Tasks/Scripts/TaskItem.cs, Assets/_Scenes/MenuScene.unity
Activating a task will fade in a task now, and Deactivating a task will fade it out. Also changed GRUMBO to PlayerSettings, and made it a prefab
=> Made it so Activating a task will cause it to fade in

Assets/Camera/Camera Blends.asset, Assets/Camera/Prefabs/Cutscene Camera.prefab, Assets/Camera/Prefabs/Cutscene Camera.prefab.meta, Assets/Camera/Prefabs/Main Camera.prefab, Assets/Camera/Prefabs/Main Camera.prefab.meta, Assets/_Scenes/[YashTest]/Yash_Cinemachine.unity.meta
added room 1 cutscene cinemachine. will continue with room 2 cutscenes
=> Added camera cinemachine for cutscenes room 1

Assets/LevelObjects/EventObjects/Scripts/Fizzler.cs
Updated fizzler script so that it could trigger when the screw hits it, but not kill the player if they walked through it
=> Quick temp update to Fizzler script

Assets/Levels/Tasks/Scripts/TaskItem.cs
Room 1 has tasks hooked up and it works.
Removed resizing of subtasks when fading out tasks. Need to redo the task list thing.
=> Hooked up tasks to room 1

Assets/Decals/Decal_Parent.prefab, Assets/Levels/Checkpoints/Scripts/CheckpointTeleporter.cs, Assets/Levels/Microwave/Art/Prefabs/Room1ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab
- changes to checkpoint script, got rid of 'using unityeditor.'
- added tasklist and camera cutscenes
- collider and art polishing
=> final build for beta sprint 1

Assets/LevelObjects/EventObjects/Scripts/Fizzler.cs, Assets/LevelObjects/PickupObjects/Scripts/PickupObject.cs
Was using an AND instead of an OR. Reverted the "fix" made to the Fizzler.
=> Fixed the CanInteract check on pickup objects

Assets/LevelObjects/EventObjects/Scripts/EventObject.cs, Assets/Player/Art/Animations/Robot_ANIM_Controller.controller, Assets/Player/Scripts/PlayerController.cs, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
Also added an intellisense recommendation to EventObject.
=> Created framework for jumping/falling animation

Assets/LevelObjects/PickupObjects/Scripts/PickupObject.cs, Assets/LevelObjects/Scripts/ObjectSpawner.cs, Assets/Sound/Scripts/SoundClipObject.cs
Put the audio source check in the SoundClipObject in the wrong spot, oops. Correctly set up the Object Spawner auto respawn and spawn at start checks.
=> Fixed the fixes i made

Assets/Levels/Tasks/Prefabs/Task.prefab, Assets/Levels/Tasks/Prefabs/TaskListCanvas.prefab, Assets/Levels/Tasks/Scripts/TaskItem.cs, Assets/Levels/Tasks/Scripts/TaskListManager.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
New Tasklist is complete!!
Tasklist will now auto size through code instead of a vertical layout group.
TASK FUNCTIONS:
ActivateTask: Makes a task show up on the tasklist
CompleteTask: Will give a completion point to a task. If a Task's completion points are equal to or greater than how many is needed to complete the task then the text will be crossed out and ticked off, all of that tasks subtasks will be hidden.
DeactivateTask: Will Fadeout a task from the tasklist and then reorder the list
SUBTASK FUNCTIONS:
ActivateSubtask: Makes a task show up on the tasklist
CompleteSubtask: Will give a completion point to a subtask. If a Task's completion points are equal to or greater than how many is needed to complete the subtask then the text will be crossed out and ticked off. …
=> Emily task list overhaul 28/10

Assets/Levels/Tasks/Prefabs/TaskListCanvas.prefab, Assets/Player/Scripts/PlayerEmotion.cs, Assets/Player/Scripts/PlayerEmotion.cs.meta, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Forgot to update the TaskListCanvas prefab. this is fixed now.
=> Update to TaskListCanvas Prefab

Assets/_Scenes/[YashTest]/Yash-CinemachinePt2.unity.meta
Made a duplicate of one of existing prefab and added a cutscene when heatcoils are disabled. May need further modification in main
=> Added Heatcoil Cinemachine Cutscene

Assets/Player/Art/Animations/Robert_Jump_Down_2_ANIM.anim, Assets/Player/Art/Animations/Robert_Jump_Down_2_ANIM.anim.meta
=> Jump down animation update

Assets/Player/Scripts/PlayerEmotion.cs, Assets/_Scenes/[EmilyTest]/[UIPauseMenuTest.unity
Added the PlayerEmotions script which will be added to the player model object. To use:
FIRST make sure all the emotion materials are places into the array. 
SECOND set the index value in the PlayerEmotions component to what element the face material is in the material list on the playermodel 
THIRD call the functions in PlayerEmotions to change the face, the parameter on the event is how long you want the face to last for.
=> Added first pass of the emotions being able to change

Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/Art/VFX/ReSpawn/ReSpawn Particle.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Levels/VFX/Confetti.prefab, Assets/Levels/VFX/Confetti.prefab.meta, Assets/Sprites/Brayden2DSprites/Square_Light Orange Mat.mat
- added deactivate task for moveto task
- blocked off secret room for supernova
- changed end of room 2 text
- added confetti to mark end of level
- art and collider update
- removed the checkpoint for magnetron
=> supernova final touches

Assets/Player/Art/Animations/Robot_ANIM_Controller.controller
Increased walking speed in the player scene
=> increased walking speed

Assets/Player/Prefabs/External Player Controller.prefab, Assets/_Scenes/MenuScene.unity
Moved player model very slightly up so he no longer clips into the ground Removed the spinning microwave from the menu scene to stop the github changes with the rendertexture
=> Moved playermodel and removed low ploy microwave

Assets/Levels/Microwave/Art/Prefabs/MicrowaveEnvironmentGreybox.prefab, Assets/Levels/Microwave/Art/Prefabs/Room2ArtPrefab.prefab, Assets/Levels/Microwave/Art/Prefabs/Room3ArtPrefab.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/[PrototypingMaterials]/PitchBlack.mat, Assets/Levels/Microwave/[PrototypingMaterials]/PitchBlack.mat.meta, Assets/Levels/Microwave/[PrototypingMaterials]/TransparentBlack2.mat, Assets/Levels/Microwave/[PrototypingMaterials]/TransparentBlack2.mat.meta
- added the corridor walls for room 3
=> added first pass of corridor walls in room 3

Assets/GameManager/Prefabs/GameManager.prefab, Assets/GameManager/Scripts/GameManager.cs
Very basic Loading screen implemation, it is tied to Halen's Scene loader and Activates when that is doing all of it's loading work.
=> Added Loading screen

Assets/Camera/Scripts/RotationMatcher.cs, Assets/Camera/Scripts/RotationMatcher.cs.meta, Assets/_Scenes/PlayerScene.unity, Assets/_Scenes/[HalenTestScenes]/[LevelObjectTest].unity
Turns out the cam rotation was fucking broken so I fixed it somehow? I dunno.
=> rotation fixed

Assets/Player/Art/Animations/12-11_Robert_Walk_ANIM.fbx.meta, Assets/_Scenes/[ZoeTest]/ZoeNewWalk.unity.meta
Added final walk to the animation folder
=> Added final walk to animation folder

Assets/LevelObjects/Art/ParticlesPrefab/HeatCoilSparks.prefab, Assets/LevelObjects/EventObjects/Prefabs/Fizzler.prefab, Assets/Levels/Microwave/Art/Prefabs/Anode.prefab, Assets/Levels/Microwave/Art/Prefabs/Room3ArtPrefab.prefab, Assets/Levels/Microwave/Lighting/Lighting & VFX.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab, Assets/VFX_Resources/Materials/FlareOrange03_mat 1.mat, Assets/VFX_Resources/Materials/FlareOrange03_mat 1.mat.meta
- fixed every single railing
- changed all buttons to use electrical switches/levers
- changed entrance vent and fadeout wall behind it
- added a ring around magnetron exit
- added screw dropper in room 2
- added dropshadow to player for jump gauge
- changes to decal parent
- fixed levers not activating
- fixed naming for levers
- fixed some colliders
- added room 3 corridor wire pit
- changes to vfx parent
=> updates to microwave scene

Assets/Decals/Decal_Prefabs/WeatheringDual_Black_Decal.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab
- fixes to some probuilder materials
- prevented player from bringing screw past socket in room 3
- turned off a postprocess volume in room 1
- fixed some decals
- collider fixes
=> Brayden rushhour fixes 11/11

Assets/Player/Art/Animations/PickUp_1_ANIM.anim, Assets/Player/Art/Animations/Robot_ANIM_Controller.controller, Assets/Player/Interaction/Scripts/PlayerInteraction.cs
All pickup animations now exist in a separate layer. Pickup animation no longer has unity events for pickup logic, and no longer stops you from moving while picking something up. Holding and Grab/Drop logic now moved into PlayerInteraction. Pickup animation sped-up to fit with how picking up is now handled with force.
=> Reworked the pickup anim stuff again

Assets/LevelObjects/EventObjects/Prefabs/LaunchPad.prefab, Assets/LevelObjects/EventObjects/Scripts/LaunchPad.cs, Assets/LevelObjects/PickupObjects/Prefabs/Screw.prefab, Assets/Player/Scripts/PlayerController.cs
LayerMask in PlayerController.IsHeading was detecting the Screw, causing the player to be launched infinitely by Launchpads.
=> Fixed launchpad bug

Assets/Decals/Decal_Parent.prefab, Assets/LevelObjects/EventObjects/Prefabs/ScrewSocketA.prefab, Assets/LevelObjects/EventObjects/Prefabs/TriggerButton/LeverAnimation/OnCoverIdle.anim, Assets/LevelObjects/EventObjects/Prefabs/TriggerButton/LeverAnimation/OnCoverIdle.anim.meta, Assets/LevelObjects/EventObjects/Prefabs/TriggerButton/LeverAnimation/Trigger Lever.controller, Assets/LevelObjects/PickupObjects/Prefabs/Screw.prefab, Assets/Levels/Microwave/Art/Prefabs/GravityWallRoom3.prefab, Assets/Levels/Microwave/Lighting/Lighting & VFX.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 2 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab, Assets/Levels/VFX/MangetronWall/Border_Fresnel 2.mat, Assets/Levels/VFX/MangetronWall/Border_Fresnel 2.mat.meta, Assets/Levels/VFX/MangetronWall/Border_Fresnel.mat
- made silo in room 2 more welcoming
- tweaked particles in silo
- changed color of the silo core
- collider fixes
- fixed screw pivot
- added and changed proximity wall shader in magnetron
- changed lever light flashes
=> polishing in microwave scene

Assets/Player/Art/Animations/Robot_ANIM_Controller.controller, Assets/Player/Art/RobotMaterials/RobotLegs_MAT.mat
Updated the animation controller to the new jump parts and made Robert's leg material render both sides.
=> Animator controller update and material update

Assets/Shaders/LiamShaders/TestOutline1.mat
Colour of outline was changed to light blue to look like the original outline.
=> Outline was adjusted to look like the original

Assets/LevelObjects/EventObjects/Prefabs/TriggerButton/LeverAnimation/OnCoverIdle.anim, Assets/LevelObjects/EventObjects/Prefabs/TriggerButton/LeverAnimation/Trigger Lever.controller, Assets/Levels/Microwave/CutscenePrefab/CutsceneCameras.prefab, Assets/Levels/Microwave/RoomPrefabs/Room 1 -------- (Colliders_Art).prefab, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab
- fixed some animations
- fixed cutscene camera issues
- fixed some bugs
=> updates to micheal wave

Assets/Levels/Microwave/Art/Prefabs/GravityWallRoom3.prefab, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/NewBorderFresn_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST.shadergraph, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST.shadergraph.meta, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST_blue.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST_blue.mat.meta, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST_red.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST_red.mat.meta, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallBlue_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallRed_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/e.prefab, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/e.prefab.meta
Added test valorant shader with emission slider for programmers. a red and blue version. needs further modifying.
=> New test valorant shader added in main

ProjectSettings/EditorBuildSettings.asset, ProjectSettings/ProjectSettings.asset
Added the credits scene to the Build Settings.
Changed the game version and capitialised P2 Games correctly.
=> Quick build fixes

Assets/Levels/VFX/MangetronWall/NewBorderFresnel/Border_Fresnel 1.shadergraph, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/NewBorderFresn_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/Shader Graphs_TEST.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/Shader Graphs_TEST.mat.meta, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/TEST.shadergraph
Material name is newborderfresn_MAT. Brayden will modify to see if it works
=> Fresnel Hopefully Final Version

Assets/Camera/Scripts/[Deprecated]/SmoothObjectTracking.cs, Assets/LevelObjects/MovingLevelObjects/Prefabs/TriggeredPlatform.prefab, Assets/Levels/Microwave/AnimatedObjectsFolder/Anode/Animation/OnActivate.anim, Assets/Levels/Microwave/AnimatedObjectsFolder/Anode/Animation/OnEnd.anim, Assets/Levels/Microwave/Art/Prefabs/Anode.prefab, Assets/Levels/Microwave/CutscenePrefab/CutsceneCameras.prefab, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallBlue_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallRed_MAT.mat, Assets/Player/Prefabs/Respawn/Respawn Cam.prefab, Assets/_Scenes/PlayerScene.unity, ProjectSettings/Packages/com.unity.probuilder/Settings.json
Set up the final cutscene with the magnetron raising up with Robert on top.
Created a magnetron quick finish button that finishes the magnetron when pressed to make testing easier.
Stopped the Respawn Camera from getting stuck behind walls by adding a Cinemachine Collider to it.
=> Room 3 cutscene + shader

Assets/Levels/Microwave/Art/Prefabs/Room3ArtPrefab.prefab, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallBlue_MAT.mat, Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallRed_MAT.mat
changed the briughtness and power of valorant wall shader in magnetron
=> fixed wall shader brightness

Assets/Levels/VFX/MangetronWall/NewBorderFresnel/ValoShaderWallRed_MAT.mat
alligned cutscene for ending so it looks better-sh.
=> Fixed cutscene for ending location

Assets/Menus/Credits/Prefabs/CreditsPerson.prefab, Assets/Menus/Credits/Scripts/CreditsNamePlayer.cs, Assets/_Scenes/CreditsScene.unity
Credit names now fade in/out
Added a full credits wall
Added skip to credits
=> Credits Screen polishing

Assets/GameManager/Scripts/GameManager.cs, Assets/Levels/Microwave/AnimatedObjectsFolder/Room3CatwalkLights/Animation/OnActivate.anim, Assets/Levels/Microwave/RoomPrefabs/Room 3 -------- (Colliders_Art).prefab, Assets/Menus/Credits/Scripts/CreditsNamePlayer.cs, Assets/Sound/Prefabs/SFXController.prefab, Assets/_Scenes/CreditsScene.unity, Assets/_Scenes/PlayerScene.unity
Credits skip works properly now.
Fixed titles on credits wall.
Updated catwalk light animator to play function through animation instead on enabling components. Made Light switch sound 2d
Fixed Audio glitch on start level
=> Credits fix, and sound fixes

Assets/Levels/Microwave/AnimatedObjectsFolder/Anode/Animation/OnEnd.anim
- redid gravity resetting when you complete the magnetron
- redid some stuff on the anode particle vfx
- closed off the entrance to easter egg room
- fixed an object being on at the start
=> Brayden microwavepolishing 4/12

Assets/P2/Art/P2gamesLogo.png.meta, Assets/Player/Scripts/PlayerEmotion.cs, Assets/Sound/Prefabs/SFXController.prefab, Assets/_Scenes/CreditsScene.unity, ProjectSettings/ProjectSettings.asset
Changes made for the final Gold build.
=> Gold Changes
